window.MUSHAVO_BUDGET_CONFIG = {
  supabaseUrl: "https://kttkospkblwvguuwnhjj.supabase.co",
  supabasePublishableKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dGtvc3BrYmx3dmd1dXduaGpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY3MDI5MDQsImV4cCI6MjEwMjI3ODkwNH0._VMG9BwYjmvYRqPKSpgv6wjqMgbKTW13XnMZaF6H07Q"
};
